### ISSUE TITLE
Nav suggestion

### ISSUE THREAD

**Issue by ckdextergames** [DonovanMods/project_daedalus#2]
Currently, clicking on the line for a mod (incl the mod name, modder name, or short description) takes one to the page with more info on the mod. But users wouldn't know that unless they just stumbled into it. Perhaps a short blurb at the top of the page like, "click a mod name for more info" or something... Thx

**Comment by dyoung522** [comment]
Great idea.

**Comment by dyoung522** [comment]
Fixed
